# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daniel Drack
title: Senior DevOps Engineer | Consultant | Community Organizer 
email: daniel@drackthor.me
# website: https://drackthor.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: drack_thor
github_username:  DrackThor
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: daniel-drack-b2b160146
xing_username: Daniel_Drack
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: DrackThor
  icon: fas fa-globe
  url: https://drackthor.me
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/daniel2hoch.jpg
about_content: |
  Hi, I'm Daniel! :D

  I'm an IT guy from Austria who's quite into sports, food, drinks and spending time with friends whenever possible.<br>
  My job is to build and design elegant and functional IT systems and their environments.<br>
  I started my IT carreer as an administrator for ETL and BI tools. <br>
  After that I worked some time in a data warehousing team before diving into all topics devops and cloud native.<br>
  In my current role I'm a Senior DevOps and cloud-native consultant with FullStackS GmbH.<br>
  I hold a BSc in Industrial Engineering, a MA in Innovation Management and a professional MBA in IT Management.<br>
  
  Currently I live in Graz with my girlfriend and our tomcat Manfred.<br>
  After work I enjoy to organize the Graz local CNCF community chapter, KCD Austria and engage in all things community and mentoring others.

  I'm skilled in some areas and I've learned and studied quite some stuff as well.<br>
  My current buzzwords are: <mark>k8s</mark> <mark>devops</mark> <mark>agile</mark> <mark>architecture</mark> <mark>automation</mark> <mark>integration</mark><br>


content:
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: FullStackS GmbH
        link: https://fullstacks.eu/
        # link_text: boringcompany.com
        sub_title: Senior DevOps Engineer
        caption: June 2022 - Present
        quote: >
          Talking the talk and walking the walk ;-)
        description: | # this will include new lines to allow paragraphs
          Consulting my customers on all things DevOps, Automation, Infrastructure as Code, Supply Chain and Runtime Security.
          We build platforms, teach and educate our customers and enable them to outperform their competitors.
      - layout: right
        title: AVL List GmbH
        link: https://avl.com
        # link_text: boringcompany.com
        sub_title: IT Infrastructure Specialist
        caption: January 2019 - June 2022
        quote: >
          Building AVL's internal DevOps platform.
        description: | # this will include new lines to allow paragraphs
          I helped in developing the AVL internal DevOps platform. My go-to buzzwords were <mark>Ansible</mark>, <mark>Artifact Management</mark>, <mark>K8s</mark>, <mark>GitOps</mark>
      - layout: right
        title: ARZ Allgemeines Rechenzentrum GmbH
        link: https://www.arz.at/
        # link_text: boringcompany.com
        sub_title: Administrator & Information Architect
        caption: March 2014 - December 2018
        quote: >
          Regulatory DataWarehouse ETL Admin and Information Architect
        description: | # this will include new lines to allow paragraphs
          My team built, maintained and operated a central Data Warehouse for finance regulatory purpuse. I was responsible for administering the ETL and BI platforms, as well as developing ETL jobs.

  - title: Academics # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AIM - Austrian Institute of Management
        caption: 2021 - 2023
        sub_title: MBA IT Management
        # quote: >
        #   We accompany motivated people.
        description: | # this will include new lines to allow paragraphs
          Classes in management, controlling, leadership, IT and enterprise architecture.<br>
          Focused on IT management.
      - layout: left
        title: Campus02 - university of applied sciences
        caption: 2019 - 2021
        sub_title: MA Innovation Management
        # quote: >
        #   We accompany motivated people.
        description: | # this will include new lines to allow paragraphs
          Classes in management, marketing, leadership, law and business development.<br>
          Focused on innovation management.
      - layout: left
        title: MCI - Management Center Innsbruck
        caption: 2015 - 2018
        sub_title: BSc Industrial Engineering
        quote: >
          We accompany motivated people.
        description: | # this will include new lines to allow paragraphs
          Classes in science, engineering, management.<br>
          Focused on industrial engineering.<br>
          Foreign semester at Tunghai University, Taichnug, Taiwan. 

  - title: Speaker Track Record
    layout: text # Type of content section (list/text)
    content: |
      - [2025-07-10] four years of building k8s platforms @ WeAreDevelopers [Berlin] \
        -> [Video](https://youtu.be/D3e9VFCrD_8) | [Slides](https://drackthor.me/assets/250710_WeAreDevelopers.pdf)
      - [2025-03-18] DevOps done right: RBAC @ Navigate Kongress  \
        -> [Video](https://www.youtube.com/watch?v=HOT08CS2B-Q)
      - [2024-06-07] cloud-native software supply chain security: the hard truth @ Area41 [Zürich] \
        -> [Video](https://www.youtube.com/watch?v=gkAr51q296o) | [Slides](https://drackthor.me/assets/20240607_Area41.pdf)
      - [2024-06-06] cloud-native software supply chain security: the hard truth @ DevWeek [Online] \
        -> [Video]() | [Slides](https://drackthor.me/assets/20240606_DevWeek.pdf)
      - [2024-02-03] Fundamental Truths about Cloud Native \w Thomas Schütz @ FH Burgenland Cloud Day 2024 \
        -> [Video](https://youtu.be/KXmqC0UD1RA) | [Slides](https://cloud-day.fh-burgenland.at/wp-content/uploads/2024/02/Cloud_Talk_2.pdf)
      - [2023-09-26] Building a cloud native austria \w Thomas Schütz @ KCD Austria 2023 \
        -> [Video](https://www.youtube.com/watch?v=uwFCvTjNjqU) | [Slides](https://docs.google.com/presentation/d/11nDJeAgABxV2aDRHIw4hHuI-rft9drY3GqubKToejM0/edit?usp=sharing)
      - [2023-09-06] don't commit shit @ DevOps & Security Meetup Wien \
        -> [Slides](https://docs.google.com/presentation/d/1SEgaHn74FZSK7-GAIsWppp1spAY-nOKi03m9bScO4f0/edit?usp=sharing)
      - [2023-07-27] Essentials of Cloud Native Security @ WeAreDevelopers World Congress 2023 Online \
        -> [Slides](https://docs.google.com/presentation/d/1ObCkUTVQUxjNL3Cfvt4CSdLCIKNNS56NUxRh4cMB0JQ/edit?usp=sharing)
      - [2023-04-27] "Community Building" panel discussion @ WeAreDevelopers Bits & Bytes
      - [2022-11-23] Using Kubernetes to manage your operating system \w Klaus Kämpf @ Cloud Native Graz
      - [2022-02-23] CNCF - Die Organisation hinter Kubernetes \w Jürgen Etzelstorfer @ Cloud Native Graz
      - [2021-11-24] CI/CD mit Azure DevOps & K8s @ Cloud Native Graz

# Footer
footer_show_references: true
references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
