# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daniel Drack
title: DevOps Engineer | Enterprise Architect | Community Organizer 
email: daniel.drack@gmx.at
# website: https://drackthor.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: drack_thor
github_username:  DrackThor
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: daniel-drack-b2b160146
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://drackthor.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: |
  Hi, I'm Daniel! :D

  I'm an IT guy from Austria who's quite into sports, food and cool drinks.<br>
  My job is to build and design elegant and functional IT systems and their environments.<br>
  I engage in connecting academic and professional communities.<br>

  I'm skilled in some areas and I've learned and studied quite some stuff as well.<br>
  My current buzzwords are: <mark>k8s</mark> <mark>devops</mark> <mark>agile</mark> <mark>architecture</mark> <mark>automation</mark> <mark>integration</mark>

content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

#   - title: Experience # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: left
#         title: The Boring Company
#         link: boringcompany.com
#         # link_text: boringcompany.com
#         sub_title: Senior Network System Administrator
#         caption: November 2017 - Present
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#             Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Academics # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MCI - Management Center Innsbruck
        caption: 2015 - 2018
        sub_title: BSc Industrial Engineering
        quote: >
          We accompany motivated people.
        description: | # this will include new lines to allow paragraphs
          Classes in science, engineering, management.<br>
          Focused on industrial engineering.<br>
          Foreign semester at Tunghai University, Taichnug, Taiwan. 
      - layout: left
        title: Campus02 - university of applied sciences
        caption: 2019 - 2021
        sub_title: MA Innovation Management
        # quote: >
        #   We accompany motivated people.
        description: | # this will include new lines to allow paragraphs
          Classes in management, marketing, leadership, law and business development.<br>
          Focused on innovation management.
      - layout: left
        title: AIM - Austrian Institute of Management
        caption: 2021 - 2023
        sub_title: MBA IT Management
        # quote: >
        #   We accompany motivated people.
        description: | # this will include new lines to allow paragraphs
          Classes in management, controlling, leadership, IT and enterprise architecture.<br>
          Focused on IT management.

  # - title: A Little More About Me
    # layout: text
    # content: | # this will include new lines to allow paragraphs
      # Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      # - Rock climbing
      # - Gaming
      # - Knitting
      # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      # Look at this cool image  
      # ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
